spring:
  application:
    name: @project.artifactId@
  main:
    banner-mode: log
  config:
    import: configtree:config/
  codec:
    log-request-details: on

server:
  port: 8080

spring.jpa:
  show_sql: true
  properties.hibernate:
    format_sql: true
    use_sql_comments: true

management:
  server:
    port: @management.port@
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics

debug: off
trace: off
logging:
  file:
    name: /var/log/spring-boot/@build.name@.log
  level:
    root: error
    web: trace
    org:
      hibernate:
        type: trace
